name: "[1] On Push"

on:
  push:
    branches: ["first"]
    paths: ["first/**"]
  workflow_dispatch:

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
